version: "3.3"

networks: 
  obrio_network:
    driver: bridge

services: 
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ../:/application
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    links: 
      - 'php_fpm'
    networks: 
      - obrio_network
  
  php_fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    links: 
      - 'postgres'
    networks: 
      - obrio_network

  postgres:
    image: library/postgres:12.3
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ../docker/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ../docker/postgres/logs/:/var/log/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - obrio_network

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - obrio_network

  queue_worker:
    build:
      context: ../
      dockerfile: docker/php_cli/Dockerfile
    working_dir: /application
    volumes:
      - ../:/application
    command: ["php", "artisan", "queue:work"]
    networks:
      - obrio_network